version: "3.8"
services:
  node-master:
    depends_on:
      - node-slave1
      - node-slave2
    image: hadoop-spark-baseline:latest
    container_name: node-master
    hostname: node-master
    environment:
      - SPARK_MASTER_MODE=yarn
    tty: true
    ports:
      - "8088:8088"
      - "50070:50070"
      - "50030:50030"
      - "8080:8080"
      - "8042:8042"
      - "8888:8888"
    volumes:
      - /opt/artifacts:/opt/artifacts
    networks:
      cluster-network:
        aliases:
          - node-master
  node-slave1:
    image: hadoop-spark-baseline:latest
    container_name: node-slave1
    hostname: node-slave1
    tty: true
    ports:
      - "18042:8042"
    networks:
      cluster-network:
        aliases:
          - node-slave1
  node-slave2:
    image: hadoop-spark-baseline:latest
    container_name: node-slave2
    hostname: node-slave2
    tty: true
    ports:
      - "28042:8042"
    networks:
      cluster-network:
        aliases:
          - node-slave2
volumes:
  artifacts:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/artifacts
networks:
  cluster-network:
    driver: bridge
    ipam:
      driver: default